export type GeneratedNodeName =
  | 'RadixAvatar'
  | 'RadixBlockquote'
  | 'RadixBox'
  | 'RadixButton'
  | 'RadixCallout'
  | 'RadixCard'
  | 'RadixContainer'
  | 'RadixDialog'
  | 'RadixFlex'
  | 'RadixSwitch'
  | 'RadixText'
